handlebars:
  suffix: .html
  enabled: true

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    schema: classpath*:schema/schema.sql
    data: classpath*:schema/data.sql
  h2:
    console:
      enabled: true     # h2 console 설정